name: Build & Test

trigger:
- dev

pool:
  vmImage: 'windows-2022'

variables:
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - group: Cloudinary
  - name: var_CloudinaryApiKey
    value: $(CloudinaryApiKey)
  - name: var_CloudinaryApiSecret
    value: $(CloudinaryApiSecret)
  - name: var_CloudinaryCloudName
    value: $(CloudinaryCloudName)
  - group: Pusher
  - name: var_PusherAppId
    value: $(PusherAppId)
  - name: var_PusherCluster
    value: $(PusherCluster)
  - name: var_PusherKey
    value: $(PusherKey)
  - name: var_PusherSecret
    value: $(PusherSecret)
  - group: Radarr
  - name: var_RadarrApiBaseUrl
    value: $(RadarrApiBaseUrl)
  - name: var_RadarrApiKey
    value: $(RadarrApiKey)

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: FileTransform@1
  displayName: "Transform json for Cloudinary.Api.IntegrationTests"
  inputs:
    folderPath: 'RadarrPusherApi.Cloudinary.Api.IntegrationTests\bin\$(BuildConfiguration)\net6.0\'
    fileType: 'json'
    targetFiles: 'appsettings.json'

- task: FileTransform@1
  displayName: "Transform json for Pusher.Api.IntegrationTests"
  inputs:
    folderPath: 'RadarrPusherApi.Pusher.Api.IntegrationTests\bin\$(BuildConfiguration)\net6.0\'
    fileType: 'json'
    targetFiles: 'appsettings.json'

- task: VSTest@2
  displayName: "Run xUnit tests"
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\bin\$(BuildConfiguration)\**\RadarrPusherApi.Cloudinary.Api.IntegrationTests.dll
      **\bin\$(BuildConfiguration)\**\RadarrPusherApi.Common.Tests.dll
      **\bin\$(BuildConfiguration)\**\RadarrPusherApi.Pusher.Api.IntegrationTests.dll
      !**\obj\**
      !**\ref\**
      !**\xunit.runner.visualstudio.testadapter.dll
      !**\xunit.runner.visualstudio.dotnetcore.testadapter.dll
    searchFolder: '$(System.DefaultWorkingDirectory)'